version: "3.9"
services:

  nginx:
    image: denissa4/nginx:1.0
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - "${WEBAPP_STORAGE_HOME}:/var/www/html/bot/static"
      - "${WEBAPP_STORAGE_HOME}:/var/log/nginx"
    networks:
      bot:
        ipv4_address: 172.16.1.1
    depends_on:
      - bot
      - api-server

  api-server:
    image: denissa4/api-server-layer:latest
    environment:
      - DataSource=
      - DbUser=
      - DbPassword=
      - DbName=
      - ApiEndPoint=
      - ApiToken=
      - StaticEndPoint=
      - ssl=True
    networks:
      bot:
        ipv4_address: 172.16.1.3
    volumes:
      - "${WEBAPP_STORAGE_HOME}:/api-server/static"

  bot:
    image: "denissa4/bot-service-js:latest"
    container_name: bot
    networks:
      bot:
        ipv4_address: 172.16.1.2
    environment:
      - port=8000
      - DEBUG=true
      - nlapiurl=http://172.16.1.3/nlsql-analyzer

networks:
  bot:
    ipam:
      driver: default
      config:
        - subnet: 172.16.1.0/16